const scope = 'basisregistratie-wonen/AccommodationObjectPage';

export const LOAD_DATA_SUCCESS = `${scope}/LOAD_DATA_SUCCESS`;
export const LOAD_DATA_FAILED = `${scope}/LOAD_DATA_FAILED`;

export const LOAD_BAG_DATA = `${scope}/LOAD_BAG_DATA`;
export const LOAD_BAG_DATA_FAILED = `${scope}/LOAD_BAG_DATA_FAILED`;
export const LOAD_BAG_DATA_SUCCESS = `${scope}/LOAD_BAG_DATA_SUCCESS`;

export const LOAD_HR_DATA = `${scope}/LOAD_HR_DATA`;
export const LOAD_HR_DATA_SUCCESS = `${scope}/LOAD_HR_DATA_SUCCESS`;

export const LOAD_NUMMERAANDUIDING_DATA = `${scope}/LOAD_NUMMERAANDUIDING_DATA`;
export const LOAD_NUMMERAANDUIDING_DATA_SUCCESS = `${scope}/LOAD_NUMMERAANDUIDING_SUCCESS`;
export const LOAD_NUMMERAANDUIDING_DATA_FAILED = `${scope}/LOAD_NUMMERAANDUIDING_FAILED`;

export const LOAD_PAND_DATA = `${scope}/LOAD_PAND_DATA`;
export const LOAD_PAND_DATA_SUCCESS = `${scope}/LOAD_PAND_DATA_SUCCESS`;
export const LOAD_PAND_DATA_FAILED = `${scope}/LOAD_PAND_DATA_FAILED`;

export const LOAD_PANDLIST_DATA = `${scope}/LOAD_PANDLIST_DATA`;
export const LOAD_PANDLIST_DATA_SUCCESS = `${scope}/LOAD_PAND_DATALIST_SUCCESS`;
export const LOAD_PANDLIST_DATA_FAILED = `${scope}/LOAD_PAND_DATALIST_FAILED`;

export const LOAD_OPENBARE_RUIMTE_DATA = `${scope}/LOAD_OPENBARE_RUIMTE_DATA`;
export const LOAD_OPENBARE_RUIMTE_DATA_SUCCESS = `${scope}/LOAD_OPENBARE_RUIMTE_DATA_SUCCESS`;
export const LOAD_OPENBARE_RUIMTE_DATA_FAILED = `${scope}/LOAD_OPENBARE_RUIMTE_DATA_FAILED`;

export const LOAD_KADASTER_OBJECT_DATA = `${scope}/LOAD_KADASTER_OBJECT_DATA`;
export const LOAD_KADASTER_OBJECT_DATA_SUCCESS = `${scope}/LOAD_KADASTER_OBJECT_DATA_SUCCESS`;
export const LOAD_KADASTER_OBJECT_DATA_FAILED = `${scope}/LOAD_KADASTER_OBJECT_DATA_FAILED`;

export const LOAD_KADASTER_SUBJECT_DATA = `${scope}/LOAD_KADASTER_SUBJECT_DATA`;
export const LOAD_KADASTER_SUBJECT_DATA_SUCCESS = `${scope}/LOAD_KADASTER_SUBJECT_DATA_SUCCESS`;
export const LOAD_KADASTER_SUBJECT_DATA_FAILED = `${scope}/LOAD_KADASTER_SUBJECT_DATA_FAILED`;

export const LOAD_LIGPLAATS_DATA = `${scope}/LOAD_LIGPLAATS_DATA`;
export const LOAD_LIGPLAATS_DATA_SUCCESS = `${scope}/LOAD_LIGPLAATS_DATA_SUCCESS`;
export const LOAD_LIGPLAATS_DATA_FAILED = `${scope}/LOAD_LIGPLAATS_DATA_FAILED`;

export const LOAD_VERBLIJFSOBJECT_DATA = `${scope}/LOAD_VERBLIJFSOBJECT_DATA`;
export const LOAD_VERBLIJFSOBJECT_DATA_SUCCESS = `${scope}/LOAD_VERBLIJFSOBJECT_DATA_SUCCESS`;
export const LOAD_VERBLIJFSOBJECT_DATA_FAILED = `${scope}/LOAD_VERBLIJFSOBJECT_DATA_FAILED`;
